name: flutter_application_1
description: "Empower your parenting journey with this comprehensive mobile app, offering personalized pregnancy tracking and child development guidance right at your fingertips."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  uuid: ^4.0.0
  printing: ^5.0.0
  pdf: ^3.0.0
  flutter_timezone: ^5.0.0
  timezone: ^0.9.4
  flutter_local_notifications: ^17.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/dreamflow_icon.jpg
  remove_alpha_ios: true
